Listas: Un iterador externo
sisoputnfrba/so-commons-library pull request #127
Opened 2020-12-09 01:09 UTC by RaniAgus

Para desarrollar esta feature, me basé en el refactor en https://github.com/sisoputnfrba/so-commons-library/pull/126

Agrego una nueva estructura `t_list_iterator` que soporta las funciones básicas mencionadas acá https://github.com/sisoputnfrba/so-commons-library/issues/80 y funciona como se propone acá https://github.com/sisoputnfrba/so-commons-library/pull/78 :
```
t_list* myList = createExampleList(); 
t_list_iterator* iterator = list_iterator_start(myList);
while (list_iterator_has_next(iterator)) {
   t_myData* element = list_iterator_next();
   if (myConditionToRemove(element)) {
      list_iterator_remove(iterator);
   }
}
list_iterator_end(iterator);
```
No incluí un `add()` porque no sabría bien si la idea sería agregar el elemento nuevo en la posición de `iterator->index`, o si agregarlo después del mismo (en la posición `iterator->index + 1`). También necesitaría saber cómo debería funcionar el `next()` después de un `add()`.

Por otro lado, quizás sea una buena idea incluir un `replace()`.

2020-12-09 17:18 UTC, RaniAgus commented
Ambos `add()` se podrían implementar así:
```
void list_iterator_add_there(t_list_iterator* iterator, void* data) {
	t_link_element* new_element = list_create_element(data);
	list_link_element(iterator->self, iterator->prev, new_element, iterator->index);
	iterator->prev = new_element;
	iterator->index++;
}

void list_iterator_add_after(t_list_iterator* iterator, void* data) {
	t_link_element* new_element = list_create_element(data);
	list_link_element(iterator->self, iterator->element, new_element, iterator->index + 1);
}
```
En ambos el iterator se queda parado sobre el mismo elemento, solo que al hacer `add_there()` el index se incrementa en uno (porque se desplazó al actual uno hacia adelante), mientras que `add_after()` no hace nada pero el next va a ser el elemento recién agregado.

2021-03-19 20:19 UTC, RaniAgus commented
Algo que me olvidé de mencionar y puede ser importante: una limitación que tiene es que no se pueden hacer dos `remove()` seguidos ya que la lista no es doblemente enlazada y solo se almacena el nodo anterior. 

Esto se puede resolver haciendo que el iterador contenga en su estructura una lista de nodos previos (en lugar de solo un puntero al nodo anterior).

2021-03-24 20:15 UTC, gastonprieto commented
> Algo que me olvidé de mencionar y puede ser importante: una limitación que tiene es que no se pueden hacer dos remove() seguidos ya que la lista no es doblemente enlazada y solo se almacena el nodo anterior.

creo que podemos vivir con esto :)

2021-03-24 20:26 UTC, gastonprieto requested changes
@RaniAgus Esta bueno como quedo, la unica cosa que en principio le veo tiene que ver con los nombres de la operación de creación/destrucción

2021-03-24 20:26 UTC, gastonprieto commented on src/commons/collections/list.h
> +	t_list_iterator* list_iterator_start(t_list* list);
Te parece llamarlo `list_iterator_create` así tiene mas consistencia con el resto de las operaciones que tenemos en las commons de estructuras?

2021-03-24 20:26 UTC, gastonprieto commented on src/commons/collections/list.h
> +	 * @DESC: Obtiene el próximo elemento a iterar de la lista
Aclarar como que avanza al siguiente elemento o algo así como para denotar que es una operación con efecto?

2021-03-24 20:26 UTC, gastonprieto commented on src/commons/collections/list.h
> +	void list_iterator_end(t_list_iterator* iterator);
`list_iterator_destroy` le pondría para ser consistente con el resto de las operaciones

2021-03-24 23:58 UTC, RaniAgus commented on src/commons/collections/list.h
> +	 * @DESC: Obtiene el próximo elemento a iterar de la lista
list_iterator_step_and_get_next ?

2021-03-25 00:12 UTC, RaniAgus commented on src/commons/collections/list.h
> +	 * @DESC: Obtiene el próximo elemento a iterar de la lista
"Avanza hacia el siguiente elemento a iterar de la lista y lo devuelve" 👍🏻

2021-03-25 00:22 UTC, RaniAgus commented
@gastonprieto Pensé en va_start y va_end, pero sí, queda más coherente con create/destroy, ahí lo cambié. También arreglé la descripción sobre start

2021-03-25 00:23 UTC, RaniAgus commented
¿Opiniones sobre incluir un add() y un replace()? Incluyo a @iago64 y @matiasgarciaisaia 

> No incluí un add() porque no sabría bien si la idea sería agregar el elemento nuevo en la posición de iterator->index, o si agregarlo después del mismo (en la posición iterator->index + 1). También necesitaría saber cómo debería funcionar el next() después de un add().
> 
> Por otro lado, quizás sea una buena idea incluir un replace().

2021-03-25 12:59 UTC, iago64 commented
Creo que el `add()` y un `replace()`, si la idea es un iterator externo para recorrer la lista, me parece un poco overkill, ya que funciones para agregar cosas a las listas hay y esto lo veo como una feature para recorrerlas

2021-03-25 14:02 UTC, RaniAgus commented
Lo que había visto en el pull #78 es que la idea es recorrer la lista para causar un efecto de manera segura. `list_iterate` lo soporta pero es un poco ineficiente, ya que esta solución (a diferencia del ejemplo de arriba) recorre la lista 1+"n removes" veces:

```C
int i = 0;
t_list* myList = createExampleList();
void _remove_and_destroy_all_by_condition(void* element) {
    if (myConditionToRemove(element)) {
        list_remove(myList, i);
    } else {
        i++;
    }
}
list_iterate(myList, _remove_and_destroy_all_by_condition);
```
Además, iterate es más bien como un for_each, cualquiera que quiera implementar esto puede pensar "¿no será peligroso modificar la lista mientras la itero?"

Al add() se lo mencionó en #80 pero sinceramente no le estoy viendo un uso, por eso quería preguntar. 
En cuanto al replace(), tampoco veo un caso en donde quiera recorrer una lista para reemplazar múltiples elementos (y si quiero reemplazar uno solo, existen funciones que lo soportan), pero lo sugerí porque pensé "quizás si un add() es necesario, quizás exista un caso en el que se necesite un replace()".

Ahora que lo pienso, quizás lo mejor sería lanzar esta v1 así como está y, después, si alguien sugiere hacer más operaciones, se revisará.

2021-03-27 21:05 UTC, RaniAgus commented
Opción B: Descartar el iterador externo y hacer que la library soporte las funciones que recorren y hagan efecto, ej: [list_remove_and_destroy_all_by_condition](https://github.com/RaniAgus/so-commons-library/commit/fb66847e9737cd0ccb72d95ca3640ca73969d1eb)

2021-03-29 14:15 UTC, gastonprieto commented on src/commons/collections/list.h
> +	 * @DESC: Obtiene el próximo elemento a iterar de la lista
👍🏾

2021-03-29 14:38 UTC, gastonprieto approved these changes

2021-03-29 14:39 UTC, gastonprieto commented
Yo arrancaría con esta iteración y después vemos

2021-03-29 22:08 UTC, RaniAgus commented
Perfecto, lo voy a mergear después de #126

2021-03-30 00:15 UTC, merged